FROM node:22-alpine

WORKDIR /app

# Install dependencies first (in Docker image layer)
COPY package*.json ./
COPY nx.json ./
COPY tsconfig.base.json ./

RUN npm ci

# Then everything else
COPY . .

EXPOSE 4200

CMD ["npx", "nx", "serve", "blog", "--configuration=development", "--host", "0.0.0.0", "--port", "4200", "--poll", "1000"]
